import { useEffect, useMemo, useState } from "react";
import dayjs, { type Dayjs } from "dayjs";
import { Alert, Button, Card, Checkbox, DatePicker, Empty, Form, Input, Modal as AntModal, Popconfirm, Select, Space, Tag, Typography, message } from "antd";
import { Check, Edit3, Plus, RotateCcw, Trash2 } from "lucide-react";
import { actionsApi } from "@/lib/api";
import type { Action, NewAction, UpdateAction } from "@/types";
import Modal from "@/components/ui/Modal";
import FrogHelp from "@/components/ui/FrogHelp";

const hours = [{ value: 0.5, label: "30 分钟" }, { value: 1, label: "1 小时" }, { value: 1.5, label: "1.5 小时" }, { value: 2, label: "2 小时" }];
const cleanError = (cause: unknown) => String(cause).replace(/^Error: /, "");
const formatDate = (value?: Dayjs | string) => typeof value === "string" ? value : value?.format("YYYY-MM-DD");
const durationColor = (value: number) => value <= 0.5 ? "blue" : value <= 1 ? "cyan" : value <= 1.5 ? "orange" : "red";
const isDeadlineUrgent = (value?: string) => value ? dayjs(value).endOf("day").diff(dayjs(), "hour", true) < 72 : false;
const renderActionDates = (startDate?: string, deadline?: string) => {
  if (startDate && deadline) return <><span>{startDate}</span><span aria-hidden="true"> ~ </span><span className={isDeadlineUrgent(deadline) ? "action-deadline-urgent" : ""}>{deadline}</span></>;
  if (startDate) return <span>{startDate} 开始</span>;
  if (deadline) return <span className={isDeadlineUrgent(deadline) ? "action-deadline-urgent" : ""}>截止 {deadline}</span>;
  return <span className="action-date-meta-empty">未设置日期</span>;
};

export default function Actions() {
  const [actions, setActions] = useState<Action[]>([]); const [status, setStatus] = useState("0"); const [frog, setFrog] = useState("all"); const [editing, setEditing] = useState<Action | null | undefined>(undefined); const [resolving, setResolving] = useState<Action | null>(null); const [error, setError] = useState("");
  const load = async () => { try { setActions(await actionsApi.list()); setError(""); } catch (cause) { setError(cleanError(cause)); } };
  useEffect(() => { void load(); }, []);
  const visible = useMemo(() => actions.filter((item) => (status === "all" || String(item.status) === status) && (frog === "all" || String(item.is_frog) === frog)), [actions, status, frog]);
  const complete = async (item: Action) => { try { await actionsApi.complete(item.id); if (item.is_delegated_follow_up === 1) setResolving(item); await load(); message.success("行动已完成"); } catch (cause) { setError(cleanError(cause)); } };
  const restore = async (item: Action) => { try { await actionsApi.restore(item.id); await load(); message.success("行动已恢复"); } catch (cause) { setError(cleanError(cause)); } };
  const remove = async (item: Action) => { try { await actionsApi.delete(item.id); await load(); message.success("行动已删除"); } catch (cause) { setError(cleanError(cause)); } };
  return <div className="page"><header className="page-header actions-header"><div><Typography.Title level={2} className="page-title">行动</Typography.Title><Typography.Paragraph className="page-subtitle">所有下一步行动都在这里，委托跟进行动也不会丢。</Typography.Paragraph></div><Button type="primary" icon={<Plus size={16} />} onClick={() => setEditing(null)}>新建行动</Button></header><div className="toolbar"><Select className="filter" value={status} onChange={setStatus} options={[{ value: "0", label: "待办" }, { value: "all", label: "全部状态" }, { value: "1", label: "已完成" }, { value: "2", label: "已放弃" }]} /><Select className="filter" value={frog} onChange={setFrog} options={[{ value: "all", label: "全部行动" }, { value: "1", label: "只看青蛙" }]} /><Typography.Text type="secondary">共 {visible.length} 条</Typography.Text></div>{error && <Alert className="page-alert" type="error" showIcon message={error} closable onClose={() => setError("")} />}<div className="record-list">{visible.length === 0 ? <div className="card"><Empty className="empty" description="还没有符合条件的行动" /></div> : visible.map((item, index) => <ActionCard key={item.id} item={item} index={index + 1} onEdit={() => setEditing(item)} onComplete={() => void complete(item)} onRestore={() => void restore(item)} onDelete={() => void remove(item)} />)}</div><ActionModal action={editing} onClose={() => setEditing(undefined)} onSaved={async () => { setEditing(undefined); await load(); }} /><DelegatedResolution action={resolving} onClose={() => setResolving(null)} onSaved={async () => { setResolving(null); await load(); }} /></div>;
}

function ActionCard({ item, index, onEdit, onComplete, onRestore, onDelete }: { item: Action; index: number; onEdit: () => void; onComplete: () => void; onRestore: () => void; onDelete: () => void }) {
  return <Card className="record-card action-card" size="small" title={<div className="action-card-title"><span className="card-index action-card-index">{index}.</span><span className={`action-card-title-text ${item.status === 1 ? "completed-title" : ""}`}>{item.title}</span>{item.is_delegated_follow_up === 1 && <Tag color="gold">委托跟进</Tag>}{item.is_frog === 1 && <Tag color="green">🐸 青蛙</Tag>}</div>} extra={<Tag color={item.status === 0 ? "blue" : item.status === 1 ? "green" : "red"}>{item.status === 0 ? "待办" : item.status === 1 ? "已完成" : "已放弃"}</Tag>}><div className="action-card-meta"><Tag color={durationColor(item.estimated_hours)}>{item.estimated_hours === 0.5 ? "30 分钟" : `${item.estimated_hours} 小时`}</Tag><span className={`action-priority ${item.importance ? "action-priority-important" : "action-priority-muted"}`}>{item.importance ? "重要" : "不重要"}</span><span className={`action-priority ${item.urgency ? "action-priority-urgent" : "action-priority-muted"}`}>{item.urgency ? "紧急" : "不紧急"}</span><span className="action-date-meta">{renderActionDates(item.start_date, item.deadline)}</span>{item.delegated_to && <span>委托给 {item.delegated_to}</span>}</div>{item.description && <Typography.Paragraph className="card-description" type="secondary">{item.description}</Typography.Paragraph>}<div className="action-card-footer"><span className="action-project-meta">所属项目：{item.project_title || "未关联"}</span><Space className="card-actions" size={4} wrap><Button size="small" type="text" icon={<Edit3 size={14} />} onClick={onEdit}>编辑</Button>{item.status === 0 ? <Button size="small" type="primary" icon={<Check size={14} />} onClick={onComplete}>完成</Button> : item.status === 1 ? <Button size="small" type="text" icon={<RotateCcw size={14} />} onClick={onRestore}>恢复</Button> : null}<Popconfirm title="确定删除这个行动吗？" onConfirm={onDelete} okText="确定" cancelText="取消"><Button size="small" danger type="text" icon={<Trash2 size={15} />} /></Popconfirm></Space></div></Card>;
}

function DelegatedResolution({ action, onClose, onSaved }: { action: Action | null; onClose: () => void; onSaved: () => Promise<void> }) { const [reason, setReason] = useState(""); if (!action) return null; const resolve = async (resolution: string) => { try { await actionsApi.resolveDelegated(action.id, resolution, resolution === "abandon" ? reason : undefined); await onSaved(); message.success("委托跟进已处理"); } catch (cause) { message.error(cleanError(cause)); } }; return <Modal open title="委托跟进已完成" onClose={onClose}><div className="form"><Typography.Paragraph>接下来如何处理事件“{action.event_title}”？</Typography.Paragraph><Space direction="vertical" className="full-width"><Button block onClick={() => void resolve("keep")}>保持已委托</Button><Button block type="primary" onClick={() => void resolve("complete")}>标记事件已完成</Button><Input.TextArea placeholder="标记放弃时填写原因" value={reason} onChange={(event) => setReason(event.target.value)} autoSize={{ minRows: 3, maxRows: 5 }} /><Button block danger disabled={!reason.trim()} onClick={() => void resolve("abandon")}>标记事件已放弃</Button></Space></div></Modal>; }

function ActionModal({ action, onClose, onSaved }: { action: Action | null | undefined; onClose: () => void; onSaved: () => Promise<void> }) {
  const [form] = Form.useForm();
  const isProjectAction = Boolean(action?.project_id);
  useEffect(() => { if (action) form.setFieldsValue({ title: action.title, description: action.description, relation: action.project_id ? `project:${action.project_id}` : action.event_id ? `event:${action.event_id}` : "none", estimated_hours: action.estimated_hours, start_date: action.start_date ? dayjs(action.start_date) : undefined, deadline: action.deadline ? dayjs(action.deadline) : undefined, importance: action.importance, urgency: action.urgency, is_frog: action.is_frog === 1 }); else if (action === null) form.setFieldsValue({ relation: "none", estimated_hours: 1, importance: 1, urgency: 1, is_frog: false }); }, [action, form]);
  if (action === undefined) return null;
  const submit = async (values: Record<string, unknown>) => { const base = { title: values.title as string, description: values.description as string || undefined, estimated_hours: Number(values.estimated_hours), start_date: formatDate(values.start_date as Dayjs | undefined), deadline: formatDate(values.deadline as Dayjs | undefined), is_frog: values.is_frog ? 1 : 0, importance: isProjectAction ? action?.importance ?? 1 : Number(values.importance), urgency: isProjectAction ? action?.urgency ?? 1 : Number(values.urgency) }; try { if (action) await actionsApi.update({ ...base, id: action.id } as UpdateAction); else await actionsApi.create(base as NewAction); await onSaved(); message.success(action ? "行动已更新" : "行动已创建"); } catch (cause) { message.error(cleanError(cause)); } };
  return <AntModal open title={action ? "编辑行动" : "新建行动"} onCancel={onClose} footer={null} destroyOnHidden><Form form={form} className="form" layout="vertical" onFinish={(values) => void submit(values)}><Form.Item name="title" label="行动标题" rules={[{ required: true, message: "请输入行动标题" }]}><Input autoFocus /></Form.Item><Form.Item name="description" label="说明"><Input.TextArea autoSize={{ minRows: 3, maxRows: 5 }} /></Form.Item><div className="form-grid action-modal-grid"><Form.Item name="estimated_hours" label="预计耗时" rules={[{ required: true, message: "请选择预计耗时" }]}><Select options={hours} /></Form.Item><Form.Item name="start_date" label="开始日期" rules={[{ required: true, message: "请选择开始日期" }]}><DatePicker className="full-width" format="YYYY-MM-DD" /></Form.Item><Form.Item name="deadline" label="截止日期"><DatePicker className="full-width" format="YYYY-MM-DD" /></Form.Item></div>{(!action || !isProjectAction) && <div className="form-grid action-priority-grid"><Form.Item name="importance" label="重要程度" rules={[{ required: true }]}><Select options={[{ value: 1, label: "重要" }, { value: 0, label: "不重要" }]} /></Form.Item><Form.Item name="urgency" label="紧急程度" rules={[{ required: true }]}><Select options={[{ value: 1, label: "紧急" }, { value: 0, label: "不紧急" }]} /></Form.Item></div>}{action && isProjectAction && <Typography.Text type="secondary" className="action-modal-hint">项目行动的重要和紧急程度由所属项目维护</Typography.Text>}<Form.Item name="is_frog" valuePropName="checked"><Checkbox>标记为青蛙 <FrogHelp /></Checkbox></Form.Item><div className="form-footer"><Button onClick={onClose}>取消</Button><Button type="primary" htmlType="submit">保存</Button></div></Form></AntModal>;
}
